config/routes.rb
FootballBet::Application.routes.draw do

root :to => 'sessions#new'

resources :users do
  member do
    get :games
    get :wagers
  end
end

resources :bank
resources :wagers
resources :games
resources :sessions, only: [:new, :create, :destroy]

match "/auth/:provider/callback" => "sessions#create"

match '/signup' => 'users#new'
match '/signin' => 'sessions#new'
match '/signout' => 'sessions#destroy'
post '/open_game' => 'users#open_game'
post '/pre_game' => 'games#create_pregame_questions'
get '/admin' => 'users#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <title>Reality Sports</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Pathway+Gothic+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=151903225009437";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


  <!-- Navigation -->
  <div id="b">
  <nav class="top-bar" id="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <a href="/">
            Reality Sports<font style="font-size: 15px;">™</font>
          </a>
        </h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user %>

          <% if current_user.admin %>
            <li class="divider"></li>
            <li><%= link_to "admin", admin_path %></li>

          <% end %>


          <% if current_user.bank != nil %>
            <li class="divider"></li>
            <li class="points"><%= link_to current_user.bank.balance.to_s + " pts", "/users/#{current_user.id}/wagers" %></li>
          <% end %>

          <li class="divider"></li>

          <li class="nav_username">
            <a href="/users/<%= current_user.id %>">
              <%= current_user.username.capitalize %></a>
          </li>

      <% end %>
        <li class="divider"></li>
        <li>
          <%= link_to "Game Lobby", games_path %>
        </li>
        <li class="divider"></li>
        <li>
          <% if current_user.nil? %>
          <%= link_to "Sign In", signin_path %>
          <% else %>
          <%= link_to "Sign Out", signout_path %>
          <% end %>
        </li>
      </ul>
    </section>
  </nav>
</div>

  <!-- End Top Bar -->

<%= yield %>

    <!-- Footer -->

      <footer class="row">
        <div class="large-12 columns"><hr>
            <div class="row">

              <div class="large-5 columns">
                  <p>&copy; Copyright Reality Sports 2013</p>
              </div>

              <div class="large-5 small-12 columns">
                  <ul class="inline-list right">
                    <li><a href="/games">Game Lobby</a></li>
                    <li><a href="#top-bar">Back To Top</a></li>
                  </ul>
              </div>

            </div>
        </div>
      </footer>

    <!-- End Footer -->


</body>
</html>